workflow finish

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -1,4 +1,4 @@
-name: Divers Production # 아예 main이랑 release를 분리해버릴까
+name: Divers Prouction
 on:
   push:
     branches:
@@ -9,18 +9,15 @@ on:
       - main
 
 jobs:
-  # test를 모두 통과하면 굳이 여기서 build를 하지 않아도 배포에 문제가 없음.
-  # CI에서 test를 하고 CD로 넘어가서 배포를 하면 되는 구조
-  # 근데 아직 test 코드가 없는 상황이니 먼저 build 해보고 넘기면 될듯.
-  # CI:
-  # test1
-  # test2
-  # test3
   CI:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout branch
         uses: actions/checkout@v4
+
+      # - name: test1
+      # - name: test2
+      # - name: test3
 
       - name: Install depndencies
         run: yarn install
@@ -28,53 +25,103 @@ jobs:
       - name: Build
         run: yarn run build
 
-  CD-Build:
-    needs: CI
-    runs-on: ubuntu_latest
+  # CD-Build:
+  #   needs: CI
+  #   environment: prod
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout branch
-        uses: actions/chekcout@v4
+  #   steps:
+  #     - name: Checkout branch
+  #       uses: actions/checkout@v4
 
-      - name: Set up Docker buildx # 나중에 action 확인해보자
-        uses: docker/setup-buildx-action@v1
+  #     - name: Create release branch
+  #       uses: peterjgrainger/action-create-branch@v3
 
-      - name: Login to DockerHub # 나중에 action 확인해보자
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Create .env file
+  #       run: |
+  #         echo PORT=${{ secrets.PORT }} >> .prod.env
+  #         echo DATABASE_HOST=${{ secrets.EC2_HOST }} >> .prod.env
+  #         echo DATABASE_PORT=${{ secrets.DB_PORT }} >> .prod.env
+  #         echo DATABASE_NAME=${{ secrets.DB_NAME }} >> .prod.env
+  #         echo DATABASE_USER=${{ secrets.DB_USER }} >> .prod.env
+  #         echo DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }} >> .prod.env
+  #         echo SECRETKEY=${{ secrets.SECRET_KEY }} >> .prod.env
+  #         echo ACCESS_EXPIRED=${{ vars.ACCESS_EXPIRED }} >> .prod.env
+  #         echo REFRESH_EXPIRED=${{ vars.REFRESH_EXPIRED }} >> .prod.env
+  #         echo SWAGGER_ID=${{ secrets.SWAGGER_ID }} >> .prod.env
+  #         echo SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }} >> .prod.env
 
-      - name: Build Docker image and push # 나중에 action 확인해보자
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          push: true
-          # tags: user/app:latest
-          # cache-from: type=gha
-          # cache-to: type=gha,mode=max
+  #     - name: Set up Docker buildx
+  #       uses: docker/setup-buildx-action@v3
 
-  CD-Deploy:
-    needs: CD-Build
-    runs-on: ubuntu-latest
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-    steps:
-      - name: Deploy to EC2
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_PRIVATEKEY }}
-          script: | # 밑에 bash 스크립트 내용 한 번 알아봅시다.
-            CONTAINER_ID=$(sudo docker ps -q --filter "publish=80-4000")
+  #     - name: Build Docker image and push
+  #       uses: docker/build-push-action@v6
+  #       with:
+  #         context: .
+  #         push: true
+  #         tags: ${{ vars.DOCKER_IMAGE }}
+  #         cache-from: type=gha
+  #         cache-to: type=gha,mode=max
 
-            if [ ! -z "$CONTAINER_ID" ]; then
-              sudo docker stop $CONTAINER_ID
-              sudo docker rm $CONTAINER_ID
-            fi
+  # CD-Deploy:
+  #   needs: CD-Build
+  #   environment: prod
+  #   runs-on: ubuntu-latest
 
-            sudo docker pull ${{ env.DOCKER_HUB }}
-            sudo docker run --name ${{ env.CONTAINER_NAME }} -d -p 80:4000 -e TZ=Asia/Seoul ${{ env.DOCKER_HUB }}
+  #   steps:
+  #     - name: Get Github Actions IP
+  #       id: IP
+  #       uses: haythem/public-ip@v1.3
 
-      - name: Create release branch
-        uses: peterjgrainger/action-create-branch@v3.0
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.IAM_ACCESS_KEY }}
+  #         aws-secret-access-key: ${{ secrets.IAM_SECRET_ACCESS_KEY }}
+  #         aws-region: 'ap-northeast-2'
+
+  #     - name: Add Github Actions IP to VPC
+  #       id: AddIP
+  #       run: |
+  #         aws ec2 authorize-security-group-ingress \
+  #             --group-id ${{ secrets.SECURITY_GROUP_ID }} \
+  #             --protocol tcp \
+  #             --port 22 \
+  #             --cidr ${{ steps.IP.outputs.ipv4 }}/32
+  #         if [ $? -eq 0 ]; then
+  #           echo "suc=true" >> $GITHUB_OUTPUT
+  #         fi
+
+  #     - name: Deploy to EC2
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.EC2_HOST }}
+  #         username: ${{ secrets.EC2_SSH_USERNAME }}
+  #         key: ${{ secrets.EC2_SSH_KEY }}
+  #         script: |
+  #           CONTAINER_ID=$(sudo docker ps -q --filter "name=${{ vars.DOCKER_CONTAINER }}")
+
+  #           if [ ! -z $CONTAINER_ID ]; then
+  #             sudo docker stop $CONTAINER_ID
+  #             sudo docker rm $CONTAINER_ID
+  #           fi
+
+  #           sudo docker pull ${{ vars.DOCKER_IMAGE }}
+  #           sudo docker run --name ${{ vars.DOCKER_CONTAINER }} -d -p 80:4000 -e TZ=Asia/Seoul ${{ vars.DOCKER_IMAGE }}
+
+  #     - name: Remove Github Actions IP from VPC
+  #       if: failure()
+  #       run: |
+  #         if [ ${{ steps.AddIP.outputs.suc }} ]; then
+  #           aws ec2 revoke-security-group-ingress \
+  #             --group-id ${{ secrets.SECURITY_GROUP_ID }} \
+  #             --protocol tcp \
+  #             --port 22 \
+  #             --cidr ${{ steps.IP.outputs.ipv4 }}/32
+  #         fi
